apiVersion: v1
kind: Service
metadata:
  name: {{ include "marvel-top-trumps-user-registration-requested.fullname" . }}
  labels:
    {{- include "marvel-top-trumps-user-registration-requested.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "marvel-top-trumps-user-registration-requested.selectorLabels" . | nindent 4 }}
